package com.model;
// Generated Aug 24, 2019 2:54:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private Integer id;
     private String fullname;
     private String email;
     private Date dob;
     private String phone;
     private String veriCode;
     private String gender;

    public Info() {
    }

    public Info(String fullname, String email, Date dob, String phone, String veriCode, String gender) {
       this.fullname = fullname;
       this.email = email;
       this.dob = dob;
       this.phone = phone;
       this.veriCode = veriCode;
       this.gender = gender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getVeriCode() {
        return this.veriCode;
    }
    
    public void setVeriCode(String veriCode) {
        this.veriCode = veriCode;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


